# Prettier configuration
# Line width
printWidth: 80
# Tabs
# Amount of spaces in a Tab
tabWidth: 2
# Use Tabs (true) or spaces
useTabs: true
# Trailing commas (if separated by lines or all in the same line)
# Default is "none"
trailingComma: 'none'
# Semicolons at the end of lines
semi: true
# Quotes
singleQuote: true
quoteProps: 'as-needed'
# Brackets
bracketSpacing: true
# Arrow Functions
# Include parentesis in single argument arrow functions
arrowParens: 'avoid'
# Parsers
overrides:
  - files:
      - '*.yml'
      - '*.yaml'
      - '.*ignore'
    options:
      parser: 'yaml'
  - files:
      - '.htmlhintrc'
      - '.stylelintrc'
      - '*.json'
    options:
      parser: 'json'
  - files: '*.css'
    options:
      parser: 'css'
  - files: '*.html'
    options:
      parser: 'html'
#
# See https://prettier.io/docs/en/options.html for all options
# JSX
# Quotes
jsxSingleQuote: false
# Brackets
jsxBracketSameLine: false
# filepath: "none"
#
#
#
# Configurations
# requirePragma: false
# insertPragma: false
# proseWrap: "preserve"
# htmlWhitespaceSensitivity: "css"
# endOfLine: "auto"
# Range of formatter
# rangeStart: 0
# rangeEnd: "Infinity"
